# This continuous integration is setting up both the CH simulation and image structure,
# and making sure that the first few iterations of both RL training work for ExaRL.

sudo: required

dist: bionic

language: python
python:
  - "3.7"

# Handle git submodules
git:
    submodules: false

 
before_install:

  - pip install -e .

  - conda install tensorflow
  - conda install pandas

  - pip install sklearn
  - pip install gym

  - conda install numba
  - conda install mpi4py

script:
  - python driver/driver_example.py