# This continuous integration is setting up both the CH simulation and image structure,
# and making sure that the first few iterations of both RL training work for ExaRL.

sudo: required

dist: bionic

language: python
python:
  - "3.7"

# Handle git submodules
git:
    submodules: false

before_install:
  - source install.sh
  - pip install -e .

script:
  - pip install -r test-requirements.txt
  - flake8 .
  - python driver/driver.py
  - pytest
