# This continuous integration is setting up both the CH simulation and image structure,
# and making sure that the first few iterations of both RL training work for ExaRL.

sudo: required

dist: bionic

language: python
python:
  - "3.7"

# Handle git submodules
git:
    submodules: false

before_install:
  - source setup/install.sh
  - pip install -e .

script:
  - pip install -r setup/test-requirements.txt
  - flake8 .
  - pytest
  - python exarl/driver
