package:
  name: dotsandboxes
  version: dev

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - pybind11
    - cmake

  run:
    - python
    - vs2015_runtime  # [win]

test:
  imports:
    - dotsandboxes

about:
  summary: Dots and boxes project built with pybind11.
