name: dab_intro_mpi
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.7
- tensorflow >=2.0.0
- keras
- seaborn
- gym
- scikit-learn
- numba
- pybind11
- ase
- lmfit
- pandas
- pip

